### ISSUE TITLE
Context drawing image has some global rendering state that can affect pixel data

### ISSUE THREAD

**Issue by bethylamine** [simon987/imagehash-web#1]
I wrestled with this all day, but with some combinations of `ctx.drawImage calls`, some will be anti-aliased and some will be aliased (regardless of image smoothing settings.) This behavior is also browser-specific, and so is the actual image produced by the draw call (in both aliased and anti-aliased modes.)

It seems like in Firefox, minified images appear to always be smoothed regardless of settings, and magnified images will honor the setting, but in Chrome, small images are drawn smooth (if instructed to) until a large image is drawn, then small images are drawn rough after that regardless of settings. This causes hash differences based on the rendering state of Chrome. Also, Chrome's "smooth" images are 'smoother' than Firefox's.

![image](https://github.com/simon987/imagehash-web/assets/130214958/1a3fa580-8790-45a6-b3a5-2d42ae465785)

These 3 images have different pixel data but were all drawn from the same image source URL.

Setting `willReadFrequently` to `true` seems to bring Chrome's behavior into line with Firefox, but again, the images they produce and thus hashes, are different.

```
const ctx = canvas.getContext("2d", {willReadFrequently: true});
```

Chrome hashes:
![image](https://github.com/simon987/imagehash-web/assets/130214958/a85f9ddd-3900-4431-b365-48a32c6b2c65)

Firefox hashes:
![image](https://github.com/simon987/imagehash-web/assets/130214958/df11f37f-b8e8-45a9-a4df-0308dd399ab8)

As you can see, they're pretty consistent with themselves but different between themselves. This presents an issue with compatibility.

With smooth scaling disabled, Chrome makes a mess of it (scaling down by a factor of about half makes a huge difference in the hash.)

![image](https://github.com/simon987/imagehash-web/assets/130214958/03548972-5d29-4b6b-9212-3b88001e3b3b)

**Comment by bethylamine** [comment]
![200w](https://github.com/simon987/imagehash-web/assets/130214958/bbacee6f-c114-4aa9-a0e7-b484ca8af2c4)

Drawing the image to a canvas at its original size does, at least, give a pixel-accurate representation between Firefox and Chrome. From there, we might need to implement our own scaling algorithm or some such to guarantee compatibility and determinism from that point onward.

**Comment by bethylamine** [comment]
I'm going to sleep now but something like Two.js might do said heavy lifting.

**Comment by simon987** [comment]
Thanks for testing! That sucks.. I changed it so that it uses the `pica` library to resize images, which should have the same behaviour across browsers. The only API change is that hash functions are async now, i.e. change `phash(...)` to `await phash(...)`.

**Comment by bethylamine** [comment]
Wow, so fast. Awesome, thanks! I'll check it out tonight. I see you added in `whash` too, nice. I had to look it up and I came across [this paper](https://www.sciencedirect.com/science/article/pii/S1877050921011030/pdf?md5=16d00461a9b1312ed235e5366e788c3c&pid=1-s2.0-S1877050921011030-main.pdf). Looks interesting!

**Comment by bethylamine** [comment]
Did you include the `pica` lib in the repository?

**Comment by bethylamine** [comment]
Could you produce a non-minified dist js for debugging purposes?

**Comment by simon987** [comment]
> Could you produce a non-minified dist js for debugging purposes?

Done!
