### ISSUE TITLE
Using web worker is blocked by CSP

### ISSUE THREAD

**Issue by bethylamine** [simon987/imagehash-web#3]
Running the hash function on an image on twitter.com gives the following error:

![image](https://github.com/simon987/imagehash-web/assets/130214958/1197b0be-aeb4-4649-9d79-d1bd7aa2816f)

I believe this has to do with `pica` using web-worker, maybe disabling that feature will help.

**Comment by simon987** [comment]
Hm I disabled it in 2f2daf965d4ea161c11780ca6f0573972208c667 let me know if it fixed it

**Comment by bethylamine** [comment]
`cib` should be diabled too since it's buggy in Chrome, which is why it's disabled by default I think

I set features to `["js", "wasm"]` and it works fine

**Comment by bethylamine** [comment]
Hoorah, successful hash matching in Twitter

![image](https://github.com/simon987/imagehash-web/assets/130214958/3e6f40be-b03c-4a4f-a663-545dd418501f)

**Comment by simon987** [comment]
> cib should be diabled too since it's buggy in Chrome

wow I love web development 🥴

I disabled cib in e96fc0c30cb286d070666e0900d2ab935e6cea55

> successful hash matching in Twitter

Nice!
